---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-depl
   labels:
      tier: frontend
spec:
   replicas: 2
   selector:
      matchLabels:
         tier: frontend
   template:
      metadata:
         labels:
            tier: frontend
      spec:
         containers:
            - name: chocolux
              image: hemanthtadikonda/chocolux
              ports:
                 - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
   name: frontend-svc
spec:
   type: LoadBalancer
   selector:
      tier: frontend
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80